### ISSUE TITLE
Not working when "Tab Groups Save and Sync" is enabled.

### ISSUE THREAD

**Issue by riddlerboss248** [loilo/auto-collapse-tab-groups#1]
The tab group is not collapsing when the "tab group save and sync" is enabled on a tab group.

**Comment by loilo** [comment]
Thanks for the report, gonna give it a try.

**Comment by loilo** [comment]
Hum. Sorry, seems like there's nothing I can currently do about this, the extension API does not allow to modify (which includes opening/closing) saved tab groups…

<img width="292" alt="image" src="https://github.com/loilo/auto-collapse-tab-groups/assets/1922624/e08b012a-bae1-4f3f-8b97-d555e7ed87f2">

As far as I can tell, this feature is not stable yet and only available behind a flag. I don't assume Google is going to change their extension API on this issue, but I'll set a reminder a couple weeks out to check this issue again.

For now, I'm going to close this as not fixable.
